export namespace UiInput {
	export type Type =
		| "textarea"
		| "color"
		| "date"
		| "datetime-local"
		| "email"
		| "month"
		| "number"
		| "url"
		| "week"
		| "search"
		| "tel"
		| "text"
		| "password"
		| "submit"
		| "reset"
		| "radio"
		| "checkbox"
		| "button"
		| "file"
		| "image"
	export type Size = "large" | "default" | "small"
}
